# Funding sources for APRSdroid 9M2PJU Mod
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

buymeacoffee: 9m2pju
custom: ["https://wise.me/faizulz13"]
